remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
https://8000-firebase-djangodive-1762096411753.cluster-73qgvk7hjjadkrjeyexca5ivva.cloudworkstations.dev/
https://8000-firebase-djangodive-1762096411753.cluster-73qgvk7hjjadkrjeyexca5ivva.cloudworkstations.dev/